language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

before_install:
   # Prevent "Please tell me who you are" errors for certain DZIL configs
   - git config --global user.name  "Travis CI"
   - git config --global user.email "support@travis-ci.com"

install:
   - cpanm --quiet --notest --skip-satisfied RJBS/Mixin-Linewise-0.100-TRIAL.tar.gz RJBS/Data-Section-0.200002-TRIAL.tar.gz RJBS/Dist-Zilla-5.003-TRIAL.tar.gz 
   - dzil authordeps | grep -v Dist::Zilla::Plugin::Encoding | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --verbose --notest --skip-satisfied
   - cpanm --quiet --skip-installed Test::Manifest Test::File Encode
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet

script:
   - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - dzil smoke --release --author --automated
